version: "3.9"
services:
  redis-server:
    image: 'redis'
  backend:
    build: backend
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
  vue-frontend:
    build: vue-frontend
    ports:
      - "8080:8080"
