version: "2.2"
services:
  redis:
    image: 'redis'
  backend:
    build: backend
    depends_on:
      - redis
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
  vue-frontend:
    build: vue-frontend
    depends_on: 
      - backend
    ports:
      - "8080:8080"
